/* Gestion Alquiler Mininos V12.1: avisos pagados + calculadora */
(() => {
'use strict';
const taxCfg={IBI:{date:'ibiDate',paid:'ibiPaidByYear'},'Tasa de basura':{date:'wasteDate',paid:'wastePaidByYear'}};
function taxPaid(p,type,year){return p?.[taxCfg[type].paid]?.[year]||''}
function markTaxPaid(id,type,year){if(isViewer())return alert('Este dispositivo está en modo solo lectura.');const p=prop(id),c=taxCfg[type];if(!p||!c)return;if(!confirm(`¿Marcar ${type} de ${p.name} como pagado en ${year}?`))return;p[c.paid]=p[c.paid]||{};p[c.paid][year]=today();persist()}
function undoTaxPaid(id,type,year){if(isViewer())return;const p=prop(id),c=taxCfg[type];if(!p?.[c?.paid]?.[year])return;if(!confirm(`¿Volver a dejar pendiente ${type} de ${p.name} en ${year}?`))return;delete p[c.paid][year];persist()}
const homeBase=renderHome;
renderHome=function(){homeBase();const box=E('alerts');[...box.querySelectorAll('.alert')].forEach(card=>{const oc=card.getAttribute('onclick')||'',m=oc.match(/property:(IBI|Tasa de basura):([^:']+):(\d{4}-\d{2}-\d{2})/);if(!m)return;const[,type,id,due]=m,p=prop(id),year=due.slice(0,4);if(taxPaid(p,type,year)){card.remove();return}card.removeAttribute('onclick');card.classList.remove('reviewed');const hint=card.querySelector('.muted');if(hint)hint.textContent='Puedes pagarlo por adelantado y quitar este aviso.';const a=document.createElement('div');a.className='icon-actions';a.innerHTML=`<button class="secondary" onclick="event.stopPropagation();showProperty('${id}')">Ver piso</button>${isViewer()?'':`<button onclick="event.stopPropagation();markTaxPaid('${id}','${type}','${year}')">Marcar como pagado</button>`}`;card.appendChild(a)});if(!box.querySelector('.alert'))box.innerHTML='<div class="empty">Sin avisos</div>'};
const propertyBase=showProperty;
showProperty=function(id){propertyBase(id);const p=prop(id),grid=E('detailBody')?.querySelector('.detail-grid');if(!p||!grid)return;[['IBI',p.ibiDate],['Tasa de basura',p.wasteDate]].forEach(([type,date])=>{if(!date)return;const year=(annualDue(date)||today()).slice(0,4),paid=taxPaid(p,type,year);const d=document.createElement('div');d.className='detail-cell detail-wide';d.innerHTML=`<span>${esc(type)} ${year}</span><b class="${paid?'positive':'negative'}">${paid?'Pagado el '+fmt(paid):'Pendiente'}</b>${paid&&!isViewer()?`<div><button class="secondary" style="margin-top:8px" onclick="undoTaxPaid('${id}','${type}','${year}')">Deshacer pago</button></div>`:''}`;grid.appendChild(d)})};
window.markTaxPaid=markTaxPaid;window.undoTaxPaid=undoTaxPaid;
function pay(P,r,n){return P<=0?0:r?P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):P/n}
function sched(P,rate,payment){const r=rate/1200;let b=P,i=0,n=0;while(b>.005&&n<1200){const x=b*r,c=payment-x;if(c<=0)return{interest:Infinity,months:Infinity};b-=Math.min(b,c);i+=x;n++}return{interest:i,months:n}}
function scenario(m,extra,mode){const P=balanceAt(m),n=Math.max(1,remainingMonths(m)),r=(+m.rate||0)/1200,q=pay(P,r,n),base=sched(P,+m.rate||0,q),used=Math.min(Math.max(0,extra),P),after=P-used;if(!after)return{P,used,after,q,newQ:0,savedI:base.interest,savedM:base.months,newM:0};if(mode==='payment'){const nq=pay(after,r,n),x=sched(after,+m.rate||0,nq);return{P,used,after,q,newQ:nq,savedI:Math.max(0,base.interest-x.interest),savedM:0,newM:n}}const x=sched(after,+m.rate||0,q);return{P,used,after,q,newQ:q,savedI:Math.max(0,base.interest-x.interest),savedM:Math.max(0,base.months-x.months),newM:x.months}}
function tm(n){const y=Math.floor(n/12),m=n%12;return[y?y+' años':'',m?m+' meses':''].filter(Boolean).join(' y ')||'0 meses'}
function mountCalc(){const mount=E('calculatorMount');if(!mount||E('mortgageCalculator'))return;mount.innerHTML=`<div id="mortgageCalculator" class="card"><h3>Calculadora de amortización hipotecaria</h3><p class="muted">Simula una amortización extraordinaria sobre cualquiera de tus hipotecas.</p><div class="plan-controls"><div><label>Hipoteca</label><select id="calcMortgage"></select></div><div><label>Importe a amortizar (€)</label><input id="calcExtra" type="number" min="0" step="100" value="10000"></div><div><label>Objetivo</label><select id="calcMode"><option value="term">Reducir plazo manteniendo cuota</option><option value="payment">Reducir cuota manteniendo plazo</option></select></div></div><div class="actions" style="justify-content:flex-start"><button id="calcRun">Calcular</button><button id="calcCompare" class="secondary">Comparar todas</button></div><div id="calcResult"></div></div>`;E('calcRun').onclick=calcOne;E('calcCompare').onclick=calcAll;E('calcMode').onchange=calcOne}
function refreshCalc(){mountCalc();const s=E('calcMortgage');if(!s)return;const old=s.value;s.innerHTML=db.mortgages.map(m=>`<option value="${esc(m.id)}">${esc(prop(m.propertyId)?.name||'Vivienda')} · ${esc(m.bank)}</option>`).join('');if(db.mortgages.some(m=>m.id===old))s.value=old;if(!db.mortgages.length)E('calcResult').innerHTML='<div class="empty">Añade una hipoteca para utilizar la calculadora.</div>'}
function calcOne(){const m=db.mortgages.find(x=>x.id===E('calcMortgage')?.value);if(!m)return;const mode=E('calcMode').value,s=scenario(m,+E('calcExtra').value||0,mode);E('calcResult').innerHTML=`<div class="detail-grid">${detailCell('Capital pendiente',euro(s.P))}${detailCell('Amortización aplicada',euro(s.used))}${detailCell('Capital restante',euro(s.after))}${detailCell('Intereses estimados ahorrados',euro(s.savedI))}${mode==='payment'?detailCell('Cuota actual estimada',euro(s.q))+detailCell('Nueva cuota estimada',euro(s.newQ))+detailCell('Reducción mensual',euro(s.q-s.newQ)):detailCell('Nuevo plazo estimado',tm(s.newM))+detailCell('Tiempo ahorrado',tm(s.savedM))}</div><p class="muted">Estimación sin comisiones, seguros ni cambios futuros del tipo.</p>`}
function calcAll(){const extra=+E('calcExtra').value||0,rows=db.mortgages.map(m=>({m,s:scenario(m,extra,'term')})).sort((a,b)=>b.s.savedI-a.s.savedI);E('calcResult').innerHTML=`<div class="scroll"><table><thead><tr><th>Hipoteca</th><th>Amortización</th><th>Intereses ahorrados</th><th>Tiempo ahorrado</th></tr></thead><tbody>${rows.map((x,i)=>`<tr><td>${i?'':'★ '}${esc(prop(x.m.propertyId)?.name||'Vivienda')} · ${esc(x.m.bank)}</td><td>${euro(x.s.used)}</td><td class="positive"><b>${euro(x.s.savedI)}</b></td><td>${tm(x.s.savedM)}</td></tr>`).join('')}</tbody></table></div>`}
const futureBase=renderFuture;renderFuture=function(){futureBase();refreshCalc()};
mountCalc();refreshCalc();if(db.mortgages.length)calcOne();renderHome();
})();
